### ISSUE TITLE
Moments_in_Time_Mini.zip can't download.

### ISSUE THREAD

**Issue by yintao-xu** [DAI-Lab/RivaGAN#10]
* RivaGAN version:
* Python version:
* Operating System:

### Description

When I execute bash download.sh.
![](https://s3.bmp.ovh/imgs/2022/01/6f2527b8d87d6464.png)
http://data.csail.mit.edu/soundnet/actions3/split1/Moments_in_Time_Mini.zip
The link looks invalid
What should I do and what links need to be replaced？
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by meisa233** [comment]
I encountered the same problem

**Comment by Z1176893827** [comment]
> I encountered the same problem

did you resolve this problem ,I need help  if you did it.

**Comment by meisa233** [comment]
> 

I contacted the Marcio Fonseca who posted the link to download "Moments_in_Time_Mini.zip", but he told me that he doen't have the link to the dataset and suggested me to contact the team that made this dataset.
I did as he said but got no response.

But you can download the full dataset instead of the mini version from http://moments.csail.mit.edu/#download.
Choose "Moments in Time Dataset" and fill out the form, then you can get the download link.

It's too large. The size of this file is about a few hundred gigabytes.

**Comment by meisa233** [comment]
> > I encountered the same problem
> 
> did you resolve this problem ,I need help if you did it.

I contacted the Marcio Fonseca who posted the link to download "Moments_in_Time_Mini.zip", but he told me that he doesn't have the link to the dataset now and suggested me to contact the team that made this dataset.
I did as he said but got no response.

But you can download the full dataset instead of the mini version from http://moments.csail.mit.edu/#download.
Choose "Moments in Time Dataset" and fill out the form, then you can get the download link.

It's too large. The size of this file is about a few hundred gigabytes.

By the way, I use another dataset called "hollywood2" to train my model. I got good result. But I don't know if the Moments_in_Time_Mini dataset will help me to train a different model.

**Comment by Z1176893827** [comment]
> > > I encountered the same problem
> > 
> > 
> > did you resolve this problem ,I need help if you did it.
> 
> I contacted the Marcio Fonseca who posted the link to download "Moments_in_Time_Mini.zip", but he told me that he doesn't have the link to the dataset now and suggested me to contact the team that made this dataset. I did as he said but got no response.
> 
> But you can download the full dataset instead of the mini version from http://moments.csail.mit.edu/#download. Choose "Moments in Time Dataset" and fill out the form, then you can get the download link.
> 
> It's too large. The size of this file is about a few hundred gigabytes.

I see,Thanks for your reply, and I want to know this project  works properly  when you download all the datasets, Thanks for your help again!

**Comment by Z1176893827** [comment]
> > > I encountered the same problem
> > 
> > 
> > did you resolve this problem ,I need help if you did it.
> 
> I contacted the Marcio Fonseca who posted the link to download "Moments_in_Time_Mini.zip", but he told me that he doesn't have the link to the dataset now and suggested me to contact the team that made this dataset. I did as he said but got no response.
> 
> But you can download the full dataset instead of the mini version from http://moments.csail.mit.edu/#download. Choose "Moments in Time Dataset" and fill out the form, then you can get the download link.
> 
> It's too large. The size of this file is about a few hundred gigabytes.

I see,Thanks for your reply, and I want to know this project  works properly  when you download all the datasets, Thanks for your help again!

> 

I see , thanks for your reply, I have download  the dataset called "hollywood2", I  will try to  debug this project later 。

**Comment by Z1176893827** [comment]
> > > I encountered the same problem
> > 
> > 
> > did you resolve this problem ,I need help if you did it.
> 
> I contacted the Marcio Fonseca who posted the link to download "Moments_in_Time_Mini.zip", but he told me that he doesn't have the link to the dataset now and suggested me to contact the team that made this dataset. I did as he said but got no response.
> 
> But you can download the full dataset instead of the mini version from http://moments.csail.mit.edu/#download. Choose "Moments in Time Dataset" and fill out the form, then you can get the download link.
> 
> It's too large. The size of this file is about a few hundred gigabytes.
> 
> By the way, I use another dataset called "hollywood2" to train my model. I got good result. But I don't know if the Moments_in_Time_Mini dataset will help me to train a different model.

Excuse me, could you please tell me whether this project is run under Win or Linux? Could you share your debugging steps or give me some suggestions on my debugging steps? After I downloaded the data set in Win, I still couldn't debug it well。
My steps are as follows: 
1.After forking the project, Conda creates a virtual environment and then pulls the master branch, the readme file prompts
      git checkout stable   
      make install
2.The two commands failed to run, so manually switch to the Production branch, CD to the data folder and run the bash download.sh command to download the data set. After downloading Hollywood2, run the command
    from RivaGAN.rivagan.rivagan import RivaGAN
    model = RivaGAN()
    model.fit("data/hollywood2",epochs=300)
still failed.    ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by meisa233** [comment]
> > > > I encountered the same problem
> > > 
> > > 
> > > did you resolve this problem ,I need help if you did it.
> > 
> > 
> > I contacted the Marcio Fonseca who posted the link to download "Moments_in_Time_Mini.zip", but he told me that he doesn't have the link to the dataset now and suggested me to contact the team that made this dataset. I did as he said but got no response.
> > But you can download the full dataset instead of the mini version from http://moments.csail.mit.edu/#download. Choose "Moments in Time Dataset" and fill out the form, then you can get the download link.
> > It's too large. The size of this file is about a few hundred gigabytes.
> > By the way, I use another dataset called "hollywood2" to train my model. I got good result. But I don't know if the Moments_in_Time_Mini dataset will help me to train a different model.
> 
> Excuse me, could you please tell me whether this project is run under Win or Linux? Could you share your debugging steps or give me some suggestions on my debugging steps? After I downloaded the data set in Win, I still couldn't debug it well。 My steps are as follows: 1.After forking the project, Conda creates a virtual environment and then pulls the master branch, the readme file prompts git checkout stable make install 2.The two commands failed to run, so manually switch to the Production branch, CD to the data folder and run the bash download.sh command to download the data set. After downloading Hollywood2, run the command from RivaGAN.rivagan.rivagan import RivaGAN model = RivaGAN() model.fit("data/hollywood2",epochs=300) still failed. ValueError: num_samples should be a positive integer value, but got num_samples=0

I don't know how to make it run on Windows.
I run it on Ubuntu 20.04.

The repo doesn't have stable branch, so I git clone from its master branch.
```
git clone git@github.com:DAI-Lab/RivaGAN.git ( OR git clone https://github.com/DAI-Lab/RivaGAN.git)
cd RivaGAN
make install
```
After you download the dataset, you should run the next lines after the line that download dataset.
```
cd data/
tar -zxvf Hollywood2-actions.tar.gz
mv Hollywood2 hollywood2
mkdir hollywood2/train
mv hollywood2/AVIClips/*train*.avi hollywood2/train/
mkdir hollywood2/val
mv hollywood2/AVIClips/*test*.avi hollywood2/val/
```
You should make sure that the hollywood2 folder is in data/.
Because the version of my PyTorch is 1.11, I did some changes to dct.py and _dct.py in venv/lib/torch_dct folder.

The lines in my train.py is as follows
```
from rivagan import RivaGAN

model = RivaGAN()
model.fit("data/hollywood2", epochs=300)
model.save("./model.pt")
```
Then it can run normally.

I don't know what's causing your problem, but it works fine on Ubuntu.

**Comment by yintao-xu** [comment]
I found this dataset,If it helps you.
The link will expire on May 25, 2022.
https://1oveshare-my.sharepoint.com/:u:/g/personal/cangku_1oveshare_onmicrosoft_com/EZrfyHmVFqlOkVKE6pV5ry8BDZy5mcfykghW202zlTCQMw?e=5iLX8v

**Comment by meisa233** [comment]
> I found this dataset,If it helps you. The link will expire on May 25, 2022. https://1oveshare-my.sharepoint.com/:u:/g/personal/cangku_1oveshare_onmicrosoft_com/EZrfyHmVFqlOkVKE6pV5ry8BDZy5mcfykghW202zlTCQMw?e=5iLX8v

Thank you.

**Comment by Z1176893827** [comment]
> I found this dataset,If it helps you. The link will expire on May 25, 2022. https://1oveshare-my.sharepoint.com/:u:/g/personal/cangku_1oveshare_onmicrosoft_com/EZrfyHmVFqlOkVKE6pV5ry8BDZy5mcfykghW202zlTCQMw?e=5iLX8v

Do you know how to check whether the extracted watermark is correct? I have submitted a new question. Could you help me check it

**Comment by Z1176893827** [comment]
> > I found this dataset,If it helps you. The link will expire on May 25, 2022. https://1oveshare-my.sharepoint.com/:u:/g/personal/cangku_1oveshare_onmicrosoft_com/EZrfyHmVFqlOkVKE6pV5ry8BDZy5mcfykghW202zlTCQMw?e=5iLX8v
> 
> Thank you.

Do you know how to check whether the extracted watermark is correct? I have submitted a new question. Could you help me check it
